name: Cleanup old GHCR images

on:
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday midnight UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: supersonic
          package-type: container
          min-versions-to-keep: 3
          delete-only-untagged-versions: false
