name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build (test)
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        run: pnpm build

      - name: Register SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.BUILD_SERVER_PORT }} -H ${{ secrets.BUILD_SERVER_IP }} 2>&1 | tee -a ~/.ssh/known_hosts

      - name: Build on Build Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          BUILD_SERVER_IP: ${{ secrets.BUILD_SERVER_IP }}
          BUILD_SERVER_USER: ${{ secrets.BUILD_SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          GIT_HASH=$(git rev-parse --short HEAD)
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          ssh -p ${{ secrets.BUILD_SERVER_PORT }} $BUILD_SERVER_USER@$BUILD_SERVER_IP "GIT_HASH=$GIT_HASH REPO_NAME=$REPO_NAME ./build.sh && GIT_HASH=$GIT_HASH REPO_NAME=$REPO_NAME ./update.sh"
